<?php

$config['platforms'] = array(
    // Windows
    'windows nt 6.1' => 'Windows Seven',
    'windows nt 6.0' => 'Windows Vista',
    'windows nt 5.2' => 'Windows 2003',
    'windows nt 5.0' => 'Windows 2000',
    'windows nt 5.1' => 'Windows XP',
    'windows nt 4.0' => 'Windows NT 4.0',
    'winnt4.0' => 'Windows NT 4.0',
    'winnt 4.0' => 'Windows NT',
    'winnt' => 'Windows NT',
    'windows 98' => 'Windows 98',
    'win98' => 'Windows 98',
    'windows 95' => 'Windows 95',
    'win95' => 'Windows 95',
    'windows' => 'Unknown Windows OS',
    // Mac
    'os x' => 'Mac OS X',
    'ppc mac' => 'Power PC Mac',
    'freebsd' => 'FreeBSD',
    'ppc' => 'Macintosh',
    // Linux
    'linux' => 'Linux',
    'debian' => 'Debian',
    // Others
    'sunos' => 'Sun Solaris',
    'opensolaris' => 'OpenSolaris',
    'beos' => 'BeOS',
    'apachebench' => 'ApacheBench',
    'aix' => 'AIX',
    'irix' => 'Irix',
    'osf' => 'DEC OSF',
    'hp-ux' => 'HP-UX',
    'netbsd' => 'NetBSD',
    'bsdi' => 'BSDi',
    'openbsd' => 'OpenBSD',
    'gnu' => 'GNU/Linux',
    'unix' => 'Unknown Unix OS',
    // Mobiles
    'android' => 'Android',
    // Gaming Consoles
    'psp' => 'PlayStation Portable',
    'playstation 3' => 'PlayStation 3',
    'bunjalloo' => 'Nintendo DS',
    'wii' => 'Wii'
);

$config['browsers'] = array(
    'flock' => 'Flock',
    'chrome' => 'Chrome',
    'opera' => 'Opera',
    'msiw' => 'Internet Explorer',
    'internet explorer' => 'Internet Explorer',
    'shiira' => 'Shiira',
    'firefox' => 'Firefox',
    'chimera' => 'Chimera',
    'phoenix' => 'Phoenix',
    'firebird' => 'Firebird',
    'camino' => 'Camino',
    'netscape' => 'Netscape',
    'omniweb' => 'OmniWeb',
    'safari' => 'Safari',
    'mozilla' => 'Mozilla',
    'konqueror' => 'Konqueror',
    'icab' => 'iCab',
    'lynx' => 'Lynx',
    'links' => 'Links',
    'hotjava' => 'HotJava',
    'amaya' => 'Amaya',
    'ibrowse' => 'IBrowse'
);

$config['mobiles'] = array(
    'android' => 'Android',
    'blackberry' => 'BlackBerry',
    'blazer' => 'Blazer',
    'bolt' => 'Bolt',
    'doris' => 'Doris',
    'dorothy' => 'Dorothy',
    'fennec' => 'Fennec',
    'gobrowser' => 'Go Browser',
    'iemobile' => 'IE Mobile',
    'iris' => 'Iris',
    'maemo browser' => 'Maemo Browser',
    'mib' => 'Motorola Internet Browser',
    'minimo' => 'Minimo',
    'mobilexplorer' => 'Mobile Explorer',
    'netfront' => 'NetFront Browser',
    'operamini' => 'Opera Mini',
    'opera mini' => 'Opera Mini',
    'operamobi' => 'Opera Mobi',
    'opera mobi' => 'Opera Mobi',
    'semc-browser' => 'SEMC-Browser',
    'skyfire' => 'Skyfire',
    'teashark' => 'TeaShark',
    'teleca' => 'Teleca-Obigo',
    'uzardweb' => 'uZard Web'
);

$config['bots'] = array(
    'abacho',
    'abcdatos',
    'abcsearch',
    'acoon',
    'adsarobot',
    'aesop',
    'ah-ha',
    'alkalinebot',
    'almaden',
    'altavista',
    'antibot',
    'anzwerscrawl',
    'aol',
    'appie',
    'arachnoidea',
    'araneo',
    'architext',
    'ariadne',
    'arianna',
    'ask',
    'aspseek',
    'asterias',
    'astraspider',
    'atomz',
    'augurfind',
    'backrub',
    'baiduspider',
    'bannana_bot',
    'bbot',
    'bdcindexer',
    'beta',
    'bingbot',
    'blindekuh',
    'boitho',
    'boito',
    'borg-bot',
    'bsdseek',
    'christcrawler',
    'coolbot',
    'cosmos',
    'crawler',
    'crawlerboy',
    'cruiser', 
    'cusco', 
    'cyveillance', 
    'deepindex', 
    'denmex',
    'dittospyder', 
    'docomo', 
    'dogpile', 
    'dtsearch', 
    'elfinbot', 
    'entire', 
    'web', 
    'esismartspider', 
    'exalead',
    'excite', 
    'ezresult', 
    'fast', 
    'fast-webcrawler', 
    'fdse', 
    'felix', 
    'fido', 
    'findwhat', 
    'finnish', 
    'firefly',
    'firstgov', 
    'fluffy', 
    'freecrawl', 
    'frooglebot', 
    'galaxy', 
    'gaisbot', 
    'geckobot', 
    'gencrawler', 
    'geobot',
    'gigabot', 
    'girafa', 
    'goclick', 
    'goliat', 
    'googlebot', 
    'griffon', 
    'gromit', 
    'grub-client', 
    'gulliver',
    'gulper', 
    'hometown', 
    'hotbot', 
    'htdig', 
    'hubater', 
    'incywincy', 
    'incrawler', 
    'indy', 
    'infoseek', 
    'ingrid',
    'intelliseek', 
    'internetseer', 
    'iron33', 
    'jcrawler', 
    'jeeves', 
    'jubii', 
    'kanoodle',
    'kapito', 
    'kit_fireball', 
    'ko_yappo_robot', 
    'kototoi', 
    'lachesis', 
    'larbin', 
    'legs',
    'linkwalker', 
    'lnspiderguy', 
    'look.com', 
    'lycos', 
    'mantraagent', 
    'markwatch', 
    'maxbot', 
    'mercator', 
    'merzscope',
    'meshexplorer', 
    'metacrawler', 
    'mirago', 
    'moget', 
    'motor', 
    'msn',
    'muscatferret', 
    'nameprotect',
    'nationaldirectory', 
    'naverrobot', 
    'nazilla', 
    'ncsa', 
    'netnose', 
    'netresearchserver',
    'northerlights', 
    'npbot', 
    'nttdirectory_robot', 
    'nutchorg',
    'odp', 
    'openbot', 
    'openfind',
    'osis-project', 
    'overture', 
    'perlcrawler', 
    'phpdig', 
    'pjspide', 
    'polybot', 
    'pompos', 
    'poppi', 
    'portalb',
    'psbot', 
    'quepasacreep', 
    'rabot', 
    'raven', 
    'rhcs', 
    'robi', 
    'robocrawl', 
    'robozilla', 
    'roverbot', 
    'scooter',
    'scrubby',
    'search',
    'searchfeed', 
    'searchspider', 
    'searchuk', 
    'seventwentyfour',
    'sidewinder', 
    'sightquestbot', 
    'skymob', 
    'sleek', 
    'slider_search', 
    'slurp', 
    'solbot', 
    'speedfind', 
    'speedy',
    'spida', 
    'spider_monkey', 
    'spiderku', 
    'stackrambler', 
    'steeler', 
    'suchbot', 
    'suntek',
    'surferf3', 
    'surfnomore', 
    'surveybot', 
    'suzuran', 
    'synobot', 
    'tarantula', 
    'teomaagent', 
    'teradex',
    'tigersuche', 
    'topiclink', 
    'toutatis', 
    'tracerlock', 
    'turnitinbot', 
    'tutorgig',
    'uaportal', 
    'uksearcher', 
    'ultraseek', 
    'unitek', 
    'vagabondo', 
    'vivisimo',
    'voilabot', 
    'voyager', 
    'vscooter', 
    'w3index', 
    'w3c_validator', 
    'wapspider', 
    'wdg_validator', 
    'webcrawler',
    'webmoose', 
    'websearchbench', 
    'webspinne', 
    'whatuseek', 
    'whizbanglab', 
    'winona',
    'wire', 
    'wotbox', 
    'wscbot', 
    'xenu', 
    'xyro', 
    'yahoobot', 
    'yahoo!',
    'yandex', 
    'zealbot', 
    'zippy', 
    'zyborg'
);
